const stoicQuotes = [
    "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
    "We suffer more often in imagination than in reality. - Seneca",
    "He who fears death will never do anything worthy of a man who is alive. - Seneca",
    "Waste no more time arguing what a good man should be. Be one. - Marcus Aurelius",
    "The best revenge is not to be like your enemy. - Marcus Aurelius",
    "Wealth consists not in having great possessions, but in having few wants. - Epictetus",
    "No man is free who is not master of himself. - Epictetus",
    "If it is not right, do not do it; if it is not true, do not say it. - Marcus Aurelius",
    "It is not death that a man should fear, but he should fear never beginning to live. - Marcus Aurelius",
    "First say to yourself what you would be; and then do what you have to do. - Epictetus",
    "Luck is what happens when preparation meets opportunity. - Seneca",
    "Man conquers the world by conquering himself. - Zeno of Citium",
    "Difficulties strengthen the mind, as labor does the body. - Seneca",
    "Do not act as if you had ten thousand years to throw away. - Marcus Aurelius",
    "To be calm is the highest achievement of the self. - Zen proverb",
    "The impediment to action advances action. What stands in the way becomes the way. - Marcus Aurelius",
    "It's not what happens to you, but how you react to it that matters. - Epictetus",
    "How long are you going to wait before you demand the best for yourself? - Epictetus",
    "The soul becomes dyed with the color of its thoughts. - Marcus Aurelius",
    "The more we value things outside our control, the less control we have. - Epictetus",
    "You could leave life right now. Let that determine what you do and say and think. - Marcus Aurelius",
    "We are more often frightened than hurt; and we suffer more from imagination than from reality. - Seneca",
    "Sometimes even to live is an act of courage. - Seneca",
    "If you want to improve, be content to be thought foolish and stupid. - Epictetus",
    "No great thing is created suddenly. - Epictetus",
    "Don't explain your philosophy. Embody it. - Epictetus",
    "He who has a why to live can bear almost any how. - Nietzsche (inspired by Stoicism)",
    "You have power over your mind, not outside events. Realize this, and you will find strength. - Marcus Aurelius",
    "True happiness is to enjoy the present, without anxious dependence upon the future. - Seneca",
    "It does not matter what you bear, but how you bear it. - Seneca",
    "Be tolerant with others and strict with yourself. - Marcus Aurelius",
    "To love only what happens, what was destined. No greater harmony. - Marcus Aurelius",
    "Wealth consists not in having great possessions, but in having few wants. - Epictetus",
    "Remember, you have been criticizing yourself for years, and it hasn't worked. Try approving of yourself and see what happens. - Epictetus",
    "What we do now echoes in eternity. - Marcus Aurelius",
    "Self-control is strength. Right thought is mastery. Calmness is power. - James Allen (Stoic-inspired)",
    "While we wait for life, life passes. - Seneca",
    "Be content to seem what you really are. - Marcus Aurelius",
    "To wish to be well is a part of becoming well. - Seneca",
    "He who lives in harmony with himself lives in harmony with the universe. - Marcus Aurelius",
    "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control. - Epictetus",
    "Let philosophy scrape off your own faults, rather than be a way to rail against the faults of others. - Seneca",
    "It is the power of the mind to be unconquerable. - Seneca",
    "We suffer more in imagination than in reality. - Seneca",
    "Know, first, who you are, and then adorn yourself accordingly. - Epictetus",
    "The whole future lies in uncertainty: live immediately. - Seneca",
    "To be stoic is not to be emotionless, but to remain unaffected by your emotions. - Unknown",
    "Take a stand. Have a clear purpose and be patient. - Epictetus",
    "The man who has anticipated the coming of troubles takes away their power when they arrive. - Seneca",
    "What is to give light must endure burning. - Viktor Frankl (Stoic-inspired)",
    "Associate with people who are likely to improve you. - Seneca",
    "The greatest obstacle to living is expectancy, which hangs upon tomorrow and loses today. - Seneca",
    "All cruelty springs from weakness. - Seneca",
    "Begin at once to live, and count each separate day as a separate life. - Seneca",
    "If it can be endured, then endure it. Stop complaining. - Marcus Aurelius",
    "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth. - Marcus Aurelius",
    "Life is very short and anxious for those who forget the past, neglect the present, and fear the future. - Seneca",
    "The trials we face are an opportunity for growth. - Epictetus",
    "To bear trials with a calm mind robs misfortune of its strength and burden. - Seneca",
    "Wealth is the slave of a wise man and the master of a fool. - Seneca",
    "Live in harmony with nature. - Zeno of Citium",
    "Only the educated are free. - Epictetus",
    "Time is like a river made up of the events which happen, and a violent stream; for as soon as a thing has been seen, it is carried away, and another comes in its place, and this will be carried away too. - Marcus Aurelius",
    "Learn to be indifferent to what makes no difference. - Marcus Aurelius",
    "Fortune falls heavily on those for whom she’s unexpected. The one always on the lookout easily endures. - Seneca",
    "Misfortune is virtue’s opportunity. - Seneca",
    "Wealth is not an end, but a means to live in accordance with nature. - Zeno of Citium",
    "The primary cause of unhappiness is never the situation but your thoughts about it. - Epictetus",
    "Fate leads the willing and drags along the reluctant. - Seneca",
    "No man is free until he learns to rule himself. - Epictetus",
    "To bear pain and misfortune is not only brave but wise. - Seneca",
    "Do not say a little in many words, but a great deal in a few. - Pythagoras (Stoic-inspired)",
    "It is not the things themselves that disturb people, but their judgments about these things. - Epictetus",
    "Difficulty shows what men are. - Epictetus",
    "He who is brave is free. - Seneca",
    "The mind adapts and converts to its own purposes the obstacle to our acting. - Marcus Aurelius",
    "You may leave this life at any moment: have this possibility in your mind in all that you do or say or think. - Marcus Aurelius"
  ];
  